[project]
name = "xian-playground"
version = "0.1.0"
description = ""
authors = [
    {name = "Endogen",email = "Endogen@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "reflex (>=0.9.0,<0.10.0)",
    "xian-tech-contracting (>=1.0.1,<2.0.0)",
    "xian-tech-linter (>=0.3.1,<1.0.0)",
    "xian-tech-py (>=0.4.8,<0.5.0)",
    "xian-tech-runtime-types (>=0.1.1,<0.2.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
xian-tech-contracting = { path = "../xian-contracting", develop = true }
xian-tech-linter = { path = "../xian-linter", develop = true }
xian-tech-py = { path = "../xian-py", develop = true }
xian-tech-runtime-types = { path = "../xian-contracting/packages/xian-runtime-types", develop = true }

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"

[tool.uv.sources]
xian-tech-contracting = { path = "../xian-contracting", editable = true }
xian-tech-linter = { path = "../xian-linter", editable = true }
xian-tech-py = { path = "../xian-py", editable = true }
xian-tech-runtime-types = { path = "../xian-contracting/packages/xian-runtime-types", editable = true }

[tool.pytest.ini_options]
pythonpath = ["."]
